local input_x = hash("key_x")
function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("UI", "enable")
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	if (action_id == input_x and action.released) then
		msg.post("UI", "disable")
	end
end
